jewelstock/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('jewelstock.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jewelstock/jewelstock/urls.py
from django.urls import path
from . import views

app_name = 'jewelstock'
urlpatterns = [
    path('', views.index, name='index'),

    # 在庫管理
    path('stock', views.stock_view, name='stock'),
    path('stock/<int:pk>', views.stock_detail_view, name='stock_detail'),
    path('stock/create', views.stock_create_view, name='stock_create'),
    path('stock/<int:pk>/edit', views.product_edit_view, name='stock_edit'),
    path('stock/<int:pk>/delete', views.stock_delete_view, name='stock_delete'),
    path('stock/existence/<int:pk>', views.stock_existence_view, name='stock_existence'),
    path('stock/create_qr/<int:pk>', views.create_qr, name='create_qr'),

    # 工程管理
    path('progress', views.progress_view, name='progress'),
    path('progress/<int:pk>/delete', views.progress_delete_view, name='progress_delete'),

    # 商品管理
    path('product', views.products_view, name='product'),
    path('product/<int:pk>', views.product_detail_view, name='product_detail'),
    path('product/create', views.product_create_view, name='product_create'),
    path('product/<int:pk>/edit', views.product_edit_view, name='product_edit'),
    path('product/<int:pk>/delete', views.product_delete_view, name='product_delete'),
]

jewelstock/jewelstock/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.conf import settings
from django.contrib.auth import get_user_model
User = get_user_model()
from django.utils import timezone
from django.utils.timezone import localtime
from django.utils.safestring import mark_safe
from django.db.models import Q

########################################################
# 1. 組織
########################################################

# j101: 作業所
class Workplace(models.Model):
    name = models.CharField(verbose_name='作業所名', max_length=50)
    address = models.CharField(verbose_name='所在地', max_length=200)
    phone_number_regex = RegexValidator(regex=r'^[0-9]{10,11}$')
    phone_number = models.CharField(verbose_name='電話番号', max_length=11, validators=[phone_number_regex])

    def __str__(self):
        return self.name
    
    def get_progresses(self):
        return Progress.objects.filter(process__workplace=self)

# aj01: 所属
class Assignment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='ユーザー', on_delete=models.CASCADE)
    workplace = models.ForeignKey(Workplace, verbose_name='作業所', on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.user.username} -> {self.workplace.name}'

# j102: 取引先
class Company(models.Model):
    name = models.CharField(verbose_name='会社名', max_length=50)
    address = models.CharField(verbose_name='所在地', max_length=200)
    phone_number_regex = RegexValidator(regex=r'^[0-9]{10,11}$')
    phone_number = models.CharField(verbose_name='電話番号', max_length=11, validators=[phone_number_regex])

    def __str__(self):
        return self.name

########################################################
# 2. 型番
########################################################

# j201: 形状
class Shape(models.Model):
    name = models.CharField(verbose_name='形状名', max_length=20)
    def __str__(self):
        return self.name
    
# j202: 型番
class ModelNumber(models.Model):
    model_number_id_regex = RegexValidator(regex=r'^[0-9]{5}$')
    model_number_id = models.PositiveIntegerField(verbose_name='型番', primary_key=True, validators=[model_number_id_regex])
    name = models.CharField(verbose_name='形状名', max_length=20)
    shape = models.ForeignKey(Shape, verbose_name='形状', on_delete=models.PROTECT)

    def __str__(self):
        str = f'[{self.shape}] {self.model_number_id} : {self.name}'
        return str

########################################################
# 3. 製品
########################################################
# j301: カテゴリグループ
class CategoryGroup(models.Model):
    name = models.CharField(verbose_name='カテゴリーグループ', max_length=20)

    def __str__(self):
        return self.name

# j302: カテゴリ
class Category(models.Model):
    name = models.CharField(verbose_name='カテゴリー', max_length=20)
    group = models.ForeignKey(CategoryGroup, verbose_name='グループ', on_delete=models.PROTECT)

    def __str__(self):
        return self.name

# j303: 製品
class Product(models.Model):
    product_code_regex = RegexValidator(regex=r'^[0-9]{14}$')
    product_code = models.PositiveIntegerField(verbose_name='商品コード', primary_key=True, validators=[product_code_regex])
    name = models.CharField(verbose_name='商品名', max_length=200)
    model_number = models.ForeignKey(ModelNumber, verbose_name='形状', on_delete=models.PROTECT)
    category = models.ManyToManyField(Category, verbose_name='カテゴリー', blank=True)
    description = models.CharField(verbose_name='商品説明', max_length=400)
    weight = models.CharField(verbose_name='重量', max_length=200, null=True, blank=True)
    size = models.CharField(verbose_name='サイズ', max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name
    
    def get_categories_str(self):
        return "\n".join([category.name for category in self.category.all()])

    def get_categories_obj(self):
        return self.category_set.all()
    
    def count_item(self):
        return Item.objects.filter(product=self).count()
    
# j304: 商品画像
def get_photos_path(instance, filename):
    return "jewelstock/product/%s/image/%s"%(str(instance.product.pk), filename)

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(verbose_name='画像',  upload_to=get_photos_path)

    def image_view(self, obj):
        return mark_safe('<img src="{}" style="width:100px height:auto;">'.format(obj.image.url))


########################################################
# 4. 素材
########################################################

# j401: 材料
class Material(models.Model):
    supplier = models.ForeignKey(Company, verbose_name='仕入れ先', on_delete=models.PROTECT)
    name = models.CharField(verbose_name='材料名', max_length=100)
    stock = models.PositiveIntegerField(verbose_name='在庫数')
    unit = models.CharField(verbose_name='単位', max_length=10)

    def __str__(self):
        return self.name

########################################################
# 5. 単品
########################################################

# j501: アイテム
class Item(models.Model):
    product = models.ForeignKey(Product, verbose_name='商品', on_delete=models.PROTECT)
    product_date = models.DateField(verbose_name='製造日', null=True, blank=True, default=None)
    sold_date = models.DateField(verbose_name='売却日', null=True, blank=True, default=None)
    item_material = models.ManyToManyField(Material, verbose_name='材料', through='ItemMaterial')

    def __str__(self):
        return f'{self.id}: {self.product.name}'
    
    def get_materials_by_item(self):
        return "\n".join([material.name for material in self.item_material.all()])
    
    def get_now_progresses(self):
        now = timezone.now()
        query = Q()
        query &= Q(item=self)
        query &= Q(start_date__lte=now)
        query &= Q(end_date__isnull=True)
        progresses = Progress.objects.filter(query)
        return progresses
    
    def get_all_progresses(self):
        return Progress.objects.filter(item=self).order_by('start_date').reverse()
    
    def get_now_existence(self):
        now = localtime(timezone.now())
        today = now.replace(hour=0, minute=0, second=0, microsecond=0)
        return ItemExistence.objects.filter(confirmed_date__gte=today, item=self.id)

# j502: 材料-アイテムの中間テーブル
class ItemMaterial(models.Model):
    item = models.ForeignKey(Item, verbose_name='単品', on_delete=models.CASCADE)
    material = models.ForeignKey(Material, verbose_name='材料', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='個数')

# j503: 店頭確認の履歴テーブル
class ItemExistence(models.Model):
    item = models.ForeignKey(Item, verbose_name='単品', on_delete=models.CASCADE)
    existence = models.BooleanField(verbose_name='店頭確認', default=False)
    confirmed_date = models.DateTimeField(verbose_name='確認日時', auto_now_add=True)

########################################################
# 6. 製造工程
########################################################
# j601: 工程
class Process(models.Model):
    operation = models.CharField(verbose_name='作業', max_length=200)
    workplace = models.ForeignKey(Workplace, verbose_name='作業所', on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.workplace}:{self.operation}'
    
# j602: 進捗
class Progress(models.Model):
    item = models.ForeignKey(Item, verbose_name='単品', on_delete=models.CASCADE)
    process = models.ForeignKey(Process, verbose_name='工程', on_delete=models.CASCADE)
    start_date = models.DateTimeField(verbose_name='開始日', null=True, blank=True, default=None)
    due_date = models.DateTimeField(verbose_name='期限', null=True, blank=True, default=None)
    end_date = models.DateTimeField(verbose_name='終了日', null=True, blank=True, default=None)
    confirmor = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="確認者", on_delete=models.SET('削除されたユーザー'), null=True, blank=True, default=None)

########################################################
# 7. 発注
########################################################
# j701: 発注
class Order(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    ordered_material = models.CharField(verbose_name='注文材料', max_length=500)
    workplace = models.ForeignKey(Workplace, verbose_name='発注場所', on_delete=models.PROTECT)
    order_date = models.DateTimeField(verbose_name='発注日時', auto_now_add=True)
    delivery_date = models.DateTimeField(verbose_name='納品日', null=True, blank=True, default=None)

########################################################
# 8. 伝票
########################################################
# j801: 取引形態
class TransactionFormat(models.Model):
    name = models.CharField(verbose_name='取引形態', max_length=10)

    def __str__(self):
        return self.name

# j802: 価格
class Price(models.Model):
    item = models.ForeignKey(Item, on_delete=models.PROTECT)
    format = models.ForeignKey(TransactionFormat, verbose_name='販売形態', on_delete=models.CASCADE)
    value = models.PositiveIntegerField(verbose_name='価格')
    start_date = models.DateField(verbose_name='開始日')
    end_date = models.DateField(verbose_name='終了日')

# j803: 伝票
class Voucher(models.Model):
    items = models.ManyToManyField(Item, verbose_name='単品', through='VoucherItem')
    format = models.ForeignKey(TransactionFormat, verbose_name='販売形態', on_delete=models.CASCADE)
    created_date = models.DateField(verbose_name='作成日')
    user_name = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="確認者", on_delete=models.SET('削除されたユーザー'), null=True, blank=True, default=None)
    workplace = models.ForeignKey(Workplace, verbose_name='販売店', on_delete=models.CASCADE)
    memo = models.CharField(verbose_name='備考', max_length=500)

jewelstock/jewelstock/forms.py
from django import forms
from .models import *
from django.utils import timezone
from django.utils.timezone import localtime
from django.core.exceptions import ValidationError

# Productフォーム
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_code', 'name', 'description', 'weight', 'size']

# 店頭確認
class ItemExistenceForm(forms.ModelForm):
    class Meta:
        model = ItemExistence
        fields = ['item', 'existence']

# Progressフォーム
class ProgressForm(forms.ModelForm):
    class Meta:
        model = Progress
        fields = ['item', 'process', 'start_date', 'due_date', 'end_date', 'confirmor']

jewelstock/templates/jewelstock/stock/confirm_existence.html
{% extends "base.html" %}
{% load bootstrap %}

{% block head_title %}confirm_item_existence - {{item.pk}}{% endblock %}
{% block body_title %}confirm_item_existence - {{item.pk}}{% endblock %}


{% block content %}

{# 基本情報 #}
<section>
    <h3 class="text-lg w-100 bg-success">店頭確認</h3>

    <div>
        {% for message in messages %}
        
        {% endfor %}
    </div>

    <form action="" method="POST" id='stock_existence_form'>
        {% csrf_token %}
        <span>この商品が店頭に存在することを確認しました。</span>
        <input type="hidden" name="item_id" value="{{ item.pk }}">
        <button type="submit">確認</button>
    </form>
</section>


{% endblock %}

{% block script %}
<script>

</script>
{% endblock %}

{% comment %} 
https://qiita.com/PoodleMaster/items/0afbce4be7e442e75be6
↑QRコード生成方法
{% endcomment %}

jewelstock/templates/jewelstock/stock/create_form.html
{% extends "base.html" %}
{% load bootstrap %}

{% block head_title %}stock - create{% endblock %}
{% block body_title %}stock - create{% endblock %}


{% block content %}
<form action="" method="POST" id="StockForm" class="form w-50 mx-auto">
    {% csrf_token %}
    <table class="table">

        {# 商品名 #}
        <tr>
            <th>商品名</th>
            <td>
                <select name="product_code">
                    {% for product in products %}
                        <option value="{{ product.product_code }}">{{ product.name }}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>

    </table>

    {# 送信ボタン #}
    <button type="submit" class="btn btn-danger d-block mx-auto">作成</button>
</form>
{% endblock %}

{% block script %}
{% endblock %}

jewelstock/templates/jewelstock/stock/detail.html
{% extends "base.html" %}
{% load bootstrap %}

{% block head_title %}stock_detail - {{item.pk}}{% endblock %}
{% block body_title %}stock_detail - {{item.pk}}{% endblock %}


{% block content %}

{# 基本情報 #}
<section>
    <h3 class="text-lg w-100 bg-success">基本情報</h3>

    <table class="table">
        <tr>
            <th>商品名</th>
            <th>アイテムID</th>
            <th>工程</th>
            <th>場所</th>
            <th>操作</th>
        </tr>

        <tr>
            <td>{{ item.product.name }}</td>
            <td>{{ item.id }}</td>
            <td>
                {% for progress in item.get_now_progresses %}
                    {{ progress.process.operation }}<br>
                {% endfor %}
            </td>
            <td>
                {% for progress in item.get_now_progresses %}
                    {{ progress.process.workplace }}<br>
                {% endfor %}
            </td>
            <td>
                <a href="{% url 'jewelstock:stock_existence' pk=item.id %}" class="btn btn-warning">店頭確認</a>
                <a href="{% url 'jewelstock:create_qr' pk=item.id %}" class="btn btn-success">QR生成</a>
                <a href="" class="btn btn-danger">売却済み</a>
                <form action="{% url 'jewelstock:stock_delete' pk=item.id %}" method="POST" class="d-inline">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">削除</button>
                </form>
            </td>
        </tr>


    </table>

</section>

{# 生産工程 #}
<section>
    <h3 class="text-lg w-100 bg-success">生産工程</h3>
    <table class="table">
        <tr>
            <th>工程</th>   
            <th>場所</th>
            <th>開始日</th>
            <th>期限</th>
            <th>終了日</th>
            <th>確認者</th>
            <th>操作</th>
        </tr>
        {% for progress in item.get_all_progresses %}
        <tr>
            <td>{{progress.process.operation}}</td>
            <td>{{progress.process.workplace}}</td>
            <td>{{progress.start_date|default:'-'}}</td>
            <td>{{progress.due_date|default:'-'}}</td>
            <td>{{progress.end_date|default:'-'}}</td>
            <td>{{progress.confirmor|default:'-'}}</td>
            {# 操作 #}
            <td>
                <form action="{% url 'jewelstock:progress_delete' pk=progress.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="path" value="{{ request.get_full_path }}">
                    <button type="submit" class="btn btn-danger">削除</button>
                </form>
                <button class="btn btn-danger">完了</button>
            </td>
        </tr>
        {% endfor %}

        {# 新規フォーム #}
        <form action="" method="POST">
        {% csrf_token %}
        <input type="hidden" name="path" value="{{ request.get_full_path }}">
        
        <tr class="bg-secondary">
            <div name="new_progress">
                {# 工程 #}
                <td colspan ="2">
                    <select name="process" class="w-100">
                        {% for process in processes %}
                            <option value="{{ process.pk }}">{{ process.operation }} - {{ process.workplace }}</option>
                        {% endfor %}
                    </select>
                </td>

                {# 開始日 #}
                <td><input type="date" name="start_date"></td>
                
                {# 期限 #}
                <td><input type="date" name="due_date"></td>

                {# 終了日 #}
                <td>-</td>

                {# 確認者 #}
                <td>-</td>

                {# 追加 #}
                <td></td>

            </div>
        </tr>

        <tr class="bg-secondary">
            <div name="new_progress">
                {# 工程 #}
                <td colspan ="2">
                    <select name="process" id="" class="w-100" placeholder="選択">
                        {% for process in processes %}
                            <option value="{{ process.pk }}">{{ process.operation }} - {{ process.workplace }}</option>
                        {% endfor %}
                    </select>
                </td>

                {# 開始日 #}
                <td><input type="date" name="start_date"></td>
                
                {# 期限 #}
                <td><input type="date" name="due_date"></td>

                {# 終了日 #}
                <td>-</td>

                {# 確認者 #}
                <td>-</td>

                {# 追加 #}
                <td></td>

            </div>
        </tr>

        {# 保存ボタン #}
        <tr>
            <td colspan="7" class="w-100 text-center bg-secondary">
                <button type="submit" class="btn btn-light">保存</button>
            </td>
        </tr>

        </form>

        {# 新規フォーム追加ボタン #}
        <tr>
            <td colspan="7" class="w-100 text-center">
                <span><button class="btn btn-light"><i class="fa-solid fa-plus"></i></button></span>
            </td>
        </tr>
    </table>
</section>

{# 材料 #}
<section>
    <h3 class="text-lg w-100 bg-success">材料</h3>
    <table class="table">
        <tr>
            <th>材料</th>   
            <th>必要数</th>
            <th>単位</th>
        </tr>
        {% for itemmaterial in item.itemmaterial_set.all %}
        <tr>
            <td>{{itemmaterial.material.name}}</td>
            <td>{{itemmaterial.quantity}}</td>
            <td>{{itemmaterial.material.unit}}</td>
        </tr>
        {% endfor %}
    </table>
</section>

{% endblock %}


{% block script %}
<script>
</script>
{% endblock %}

jewelstock/templates/jewelstock/stock/list.html
{% extends "base.html" %}
{% load bootstrap %}

{% block head_title %}stock{% endblock %}
{% block body_title %}stock{% endblock %}


{% block content %}
{# ========== 操作 ========== #}
<a href="{% url 'jewelstock:stock_create' %}" class="btn btn-primary">追加</a>

{# ========== 検索フォーム ========== #}
<form action="" class="form p-3 bg-warning">
    {# 商品名 #}
    <label>
        商品名
        <input type="text" name="keyword" value="{{ request.GET.keyword }}" id="search_form" autocomplete="off" list="search_form_result">
    </label>
    <datalist id="search_form_result"></datalist>

    {# 工程 #}
    <label>
        工程
        <select name="process" id="">
            <option value="">すべて</option>
            {% for process in processes %}
                <option value="{{ process.operation }}" {% if process.operation == request.GET.process %}selected{% endif %}>{{ process.operation }}</option>
            {% endfor %}
        </select>
    </label>

    {# 場所 #}
    <label>
        場所
        <select name="workplace" id="">
            <option value="">すべて</option>
            {% for place in workplaces %}
                <option value="{{ place.pk }}" {% if place.pk|stringformat:'s' == request.GET.workplace %}selected{% endif %}>{{ place.name }}</option>
            {% endfor %}
        </select>
    </label>

    {# 検索・リセットボタン #}
    <button type="submit" class="btn btn-primary">検索</button>
    <a href="{% url 'jewelstock:stock' %}" class="btn btn-primary">リセット</a>
</form>


{# ========== 在庫リスト ========== #}
<form action="" method="POST">
{% csrf_token %}
{% comment %} <button type="submit" class="btn btn-danger">選択アイテムを売却済みにする</button> {% endcomment %}
<table class="table">
    <tr>
        <th>選択</th>
        <th>商品名</th>
        <th>アイテムID</th>
        <th>工程</th>
        <th>場所
            <select name="workplace" id="workplace_select">
                <option value=""></option>
                <option value="">hoge</option>
                <option value="">piyo</option>
                <option value="">fuga</option>
            </select>
        </th>
        <th>店頭確認</th>
        <th>操作</th>
    </tr>

    {# エンプティステート #}
    {% if not items %}
        <tr> <td colspan="6" class="text-center">該当商品なし</td> </tr>
    {% endif %}

    {% for item in items %}
    <tr>
        {# チェックボックス #}
        <td><input type="checkbox" id="{{ item.id }}"></td>

        {# 商品名 #}
        <td><a href="{% url 'jewelstock:product_detail' pk=item.product.product_code %}">{{ item.product.name }}</a></td>

        {# ID #}
        <td>{{ item.id }}</td>

        {# 工程 #}
        <td>
            {% for progress in item.get_now_progresses %}
                {{ progress.process.operation }}<br>
            {% endfor %}
        </td>

        {# 場所 #}
        <td>
            {% for progress in item.get_now_progresses %}
                {{ progress.process.workplace }}<br>
            {% endfor %}
        </td>

        {# 店頭確認 #}
        <td>
            {% for obj in item.get_now_existence %}
                {{ obj.confirmed_date }}
            {% endfor %}
        </td>

        {# 操作 #}
        <td>
            <a href="{% url 'jewelstock:stock_detail' pk=item.id %}" class="btn btn-primary">詳細</a>
            <a href="" class="btn btn-danger">売却済み</a>
        </td>
    </tr>
    {% endfor %}

</table>
</form>
{% endblock %}


{% block script %}
<script>

// productリストの取得
const products = [
    {% for product in products %}
    "{{ product.name }}",
    {% endfor %}
];

// #search_formを取り出す
const search_form = document.querySelector("#search_form");

search_form.addEventListener("input", (event) => {
    let results = products;
    

    // スペースを半角に統一し、スペース区切り
    let words = event.currentTarget.value.replace(/　/g, " ").split(' ').filter( w => w !== "");

    for (let word of words){

        let new_results = [];

        for (let result of results){
            
            //大文字小文字を区別せずに検索
            if( result.toLowerCase().indexOf(word.toLowerCase()) !== -1 ){
                new_results.push( result );
            }
        }
        results = new_results;

    }

    //datalistに入力候補を追加
    elems = "";
    for (let result of results){
        elems += `<option value="${result}"></option>`
    }
    const seatch_form_result = document.querySelector("#search_form_result");
    search_form_result.innerHTML = elems;

})

</script>
{% endblock %}