jewelstock/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('jewelstock.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jewelstock/jewelstock/urls.py
from django.urls import path
from . import views

app_name = 'jewelstock'
urlpatterns = [
    path('', views.index, name='index'),

    # 在庫管理
    path('stock', views.stock_view, name='stock'),
    path('stock/<int:pk>', views.stock_detail_view, name='stock_detail'),
    path('stock/create', views.stock_create_view, name='stock_create'),
    path('stock/<int:pk>/edit', views.product_edit_view, name='stock_edit'),
    path('stock/<int:pk>/delete', views.stock_delete_view, name='stock_delete'),
    path('stock/existence/<int:pk>', views.stock_existence_view, name='stock_existence'),
    path('stock/create_qr/<int:pk>', views.create_qr, name='create_qr'),

    # 工程管理
    path('progress', views.progress_view, name='progress'),
    path('progress/<int:pk>/delete', views.progress_delete_view, name='progress_delete'),

    # 商品管理
    path('product', views.products_view, name='product'),
    path('product/<int:pk>', views.product_detail_view, name='product_detail'),
    path('product/create', views.product_create_view, name='product_create'),
    path('product/<int:pk>/edit', views.product_edit_view, name='product_edit'),
    path('product/<int:pk>/delete', views.product_delete_view, name='product_delete'),
]

jewelstock/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block head_title %}{% endblock %}</title>
        <link rel="shortcut icon" href=""> 
        
        {# bootstrap読み込み #}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous" defer></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" type="text/css">

        {# Google Fonts読み込み #}
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Train+One&display=swap" rel="stylesheet">
    
        {# flatpicker読み込み #}
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
        <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
        <script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/ja.js"></script>

        {# css読み込み #}
        <link rel="stylesheet" href="">

        {% block head %}{% endblock %}
    </head>

    <body>
        <header class="bg-primary"> 
            <a href="{% url 'jewelstock:index' %}" class="h2 text-warning">JewelStock</a>
            <a href="{% url 'signup' %}" class="btn btn-light m-2">会員登録</a>
            <a href="{% url 'login' %}"  class="btn btn-light m-2">ログイン</a>
            <form action="{% url 'logout' %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-light m-2">ログアウト</button>
            </form>
            
            <span>
                {% if request.user.is_authenticated %}
                    ログインしています
                {% else %}
                    ログインしていません
                {% endif %}
            </span>
        </header>

        <div class="row mx-0 h-100">

        {# サイドバー #}
        {% if request.user.is_authenticated %}
        <div class="col-lg-2 navigation h-100 bg-light">
            <ul>
                <li><a href="{% url 'jewelstock:stock' %}">在庫管理</a></li>
                <li><a href="">発注管理</a></li>
                <li><a href="{% url 'jewelstock:progress' %}">工程管理</a></li>
                <li><a href="{% url 'jewelstock:product' %}">商品管理</a></li>
                <li><a href="">売上管理</a></li>
                <li><a href="">ユーザー管理</a></li>
            </ul>
        </div>
        {% endif %}

        {# コンテンツ #}
        <div class="col-lg-10">
            <h1>
                {% block body_title%}{% endblock %}
            </h1>

            {# メッセージ欄 #}
            <div class="notify_message_area">
                {% for message in messages %}
                <div class="notify_message notify_message_{{ message.tags }}">
                        <div class="notify_message_content">{{ message }}</div>
                        <div class="notify_message_delete"><i class="fas fa-times"></i></div>
                </div>
                {% endfor %}
            </div>
            
            <div class="content m-3">
                {% block content %}{% endblock %}
            </div>
        </div>

        </div>
        {% block script %}{% endblock %}
    </body>
</html>