jewelstock/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('jewelstock.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jewelstock/jewelstock/urls.py
from django.urls import path
from . import views

app_name = 'jewelstock'
urlpatterns = [
    path('', views.index, name='index'),

    # 在庫管理
    path('stock', views.stock_view, name='stock'),
    path('stock/<int:pk>', views.stock_detail_view, name='stock_detail'),
    path('stock/create', views.stock_create_view, name='stock_create'),
    path('stock/<int:pk>/edit', views.product_edit_view, name='stock_edit'),
    path('stock/<int:pk>/delete', views.stock_delete_view, name='stock_delete'),
    path('stock/existence/<int:pk>', views.stock_existence_view, name='stock_existence'),
    path('stock/create_qr/<int:pk>', views.create_qr, name='create_qr'),

    # 工程管理
    path('progress', views.progress_view, name='progress'),
    path('progress/<int:pk>/delete', views.progress_delete_view, name='progress_delete'),

    # 商品管理
    path('product', views.products_view, name='product'),
    path('product/<int:pk>', views.product_detail_view, name='product_detail'),
    path('product/create', views.product_create_view, name='product_create'),
    path('product/<int:pk>/edit', views.product_edit_view, name='product_edit'),
    path('product/<int:pk>/delete', views.product_delete_view, name='product_delete'),
]

jewelstock/jewelstock/forms.py
from django import forms
from .models import *
from django.utils import timezone
from django.utils.timezone import localtime
from django.core.exceptions import ValidationError

# Productフォーム
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_code', 'name', 'description', 'weight', 'size']

# 店頭確認
class ItemExistenceForm(forms.ModelForm):
    class Meta:
        model = ItemExistence
        fields = ['item', 'existence']

# Progressフォーム
class ProgressForm(forms.ModelForm):
    class Meta:
        model = Progress
        fields = ['item', 'process', 'start_date', 'due_date', 'end_date', 'confirmor']

jewelstock/jewelstock/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from .models import *
from .forms import *
from django.db.models import Q
from django.contrib import messages
from django.conf import settings
import os
import pyqrcode
from django.urls import reverse, resolve

class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'jewelstock/index.html')

index = IndexView.as_view()

# =======================================
# 在庫管理
# =======================================

# 一覧
class StockView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        query = Q()

        # 検索キーワードを取得し、クエリセットに追加
        keyword = request.GET.get('keyword')
        workplace = request.GET.get('workplace')
        process = request.GET.get('process')
        
        if keyword:
            words = keyword.replace('　', ' ').split(' ')

            for word in words:
                if word == '':
                    continue
                query &= Q(product__name__icontains=word)

        if workplace:
                query &= Q(progress__process__workplace=workplace)

        if process:
                query &= Q(progress__process__operation=process)
        

        # 売却済みのアイテムを除外
        query &= Q(sold_date=None)

        # contextの生成
        items = Item.objects.filter(query)
        products = Product.objects.all()
        workplaces = Workplace.objects.all()
        processes = Process.objects.all()
        
        context['items'] = items
        context['products'] = products
        context['workplaces'] = workplaces
        context['processes'] = processes

        return render(request, 'jewelstock/stock/list.html', context)
    
    def post(self, request, *args, **kwargs):
        item_id = request.POST.get('item_id')
        return redirect('jewelstock:stock')

stock_view = StockView.as_view()

# 詳細
class StockDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        context = {}
        context['item'] = Item.objects.get(pk=pk)
        context['processes'] = Process.objects.all()
        return render(request, 'jewelstock/stock/detail.html', context)
    
    # def post(self, request, pk, *args, **kwargs):
    #     item = get_object_or_404(Item, id=pk)
    #     new_progresses = {}
    #     new_progresses['process'] = request.POST.getlist('process')
    #     new_progresses['start_date'] = request.POST.getlist('start_date')
    #     new_progresses['due_date'] = request.POST.getlist('due_date')

    #     print(new_progresses)
    #     for i in range(0, len(new_progresses['process']), 1):
    #         new_progress = {}
    #         new_progress['item'] = item
    #         new_progress['process'] = new_progresses['process'][i]
    #         new_progress['start_date'] = new_progresses['start_date'][i]
    #         new_progress['due_date'] = new_progresses['due_date'][i]

    #         form = ProgressForm(new_progress)

    #         if form.is_valid():
    #             form.save()
    #             messages.success(request, '工程を追加しました')
        
    #         else:
    #             # バリデーションNG
    #             values = form.errors.get_json_data().values()
    #             for value in values:
    #                 for v in value:
    #                     messages.error(request, v["message"])
            

    #     context = {}
    #     context['item'] = item
    #     context['processes'] = Process.objects.all()
    #     return render(request, 'jewelstock/stock/detail.html', context)

stock_detail_view = StockDetailView.as_view()

# 新規作成
class StockCreateView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        context['products'] = Product.objects.all()
        return render(request, 'jewelstock/stock/create_form.html', context)
    
    def post(self, request, *args, **kwargs):
        product = request.POST.get('product_code')
        item = Item()
        item.product = Product.objects.get(product_code=product)
        item.save()
        return redirect('jewelstock:stock')

stock_create_view = StockCreateView.as_view()

# 削除
class StockDeleteView(View):
    def post(self, request, pk, *args, **kwargs):
        item = get_object_or_404(Item, pk=pk)
        item.delete()
        print('アイテムを削除しました。')
        messages.success(request, 'アイテムを削除しました。')
        return redirect('jewelstock:stock')

stock_delete_view = StockDeleteView.as_view()


# QR生成
def create_qr(request, pk):
    url = request._current_scheme_host + reverse('jewelstock:stock_existence', args=[pk])
    filepath = f'static/jewelstock/qr/test-item-{pk}.png'
    code = pyqrcode.create(url, error='L', version=5, mode='binary')
    code.png(filepath, scale=5, module_color=[0, 0, 0, 128], background=[255, 255, 255])
    messages.success(request, 'QRコードを生成しました')
    return redirect('jewelstock:stock_detail', pk=pk)


# 店頭確認
class StockExistenceView(View):
    def get(self, request, pk, *args, **kwargs):
        # ログインしていない場合、顧客向けページを表示
        if not request.user.is_authenticated:
            context = {}
            context['product'] = Item.objects.get(pk=pk).product
            return render(request, 'jewelstock/opened_products.html', context)
        
        # ログイン済みの場合、店頭確認ページを表示
        context = {}
        context['item'] = Item.objects.get(pk=pk)
        return render(request, 'jewelstock/stock/confirm_existence.html', context)
    
    def post(self, request, *args, **kwargs):
        # ログインしていない場合、顧客向けページへリダイレクト
        if not request.user.is_authenticated:
            return
        
        # ログイン済みの場合、店頭確認の状況を記録
        item_id = request.POST.get('item_id')

        data = {}
        data['item'] = Item.objects.get(pk=item_id)
        data['existence'] = True

        print(f'data:{data}')
        form = ItemExistenceForm(data)

        if form.is_valid():
            # バリデーションOK
            print(f'店頭確認完了:{item_id}')
            form.save()
            messages.success(request, '店頭確認しました')
            return redirect('jewelstock:stock_detail', pk=item_id)
        
        else:
            # バリデーションNG

            # エラーメッセージ
            values = form.errors.get_json_data().values()
            for value in values:
                for v in value:
                    messages.error(request, v["message"])

            return redirect('jewelstock:stock_detail', pk=item_id)

stock_existence_view = StockExistenceView.as_view()



# =======================================
# 発注管理
# =======================================
# =======================================
# 工程管理
# =======================================
class ProgressView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        search_id = request.GET.get('search_id')

        context['workplaces_all'] = Workplace.objects.all()

        if search_id:
            context['workplaces'] = Workplace.objects.filter(pk=search_id)
        else:
            context['workplaces'] = context['workplaces_all']

        return render(request, 'jewelstock/progress.html', context)

progress_view = ProgressView.as_view()

class ProgressDeleteView(View):
    def post(self, request, pk, *args, **kwargs):
        path = request.POST.get('path')
        print(f'path:{path}')
        print(f'resolverMatch:{resolve(path)}')
        appname = resolve(path).app_name
        urlname = resolve(path).url_name
        id = resolve(path).kwargs['id']
        print(f'urlname:{urlname}')
        progress = get_object_or_404(Progress, pk=pk)    
        progress.delete()
        print('工程を削除しました。')
        messages.success(request, '工程を削除しました。')

        return redirect(appname + ':' + urlname, pk=id)

progress_delete_view = ProgressDeleteView.as_view()

class ProgressCreateView(View):
    def post(self, request, pk, *args, **kwargs):
        item = get_object_or_404(Item, id=pk)
        new_progresses = {}
        new_progresses['process'] = request.POST.getlist('process')
        new_progresses['start_date'] = request.POST.getlist('start_date')
        new_progresses['due_date'] = request.POST.getlist('due_date')

        print(new_progresses)
        for i in range(0, len(new_progresses['process']), 1):
            new_progress = {}
            new_progress['item'] = item
            new_progress['process'] = new_progresses['process'][i]
            new_progress['start_date'] = new_progresses['start_date'][i]
            new_progress['due_date'] = new_progresses['due_date'][i]

            form = ProgressForm(new_progress)

            if form.is_valid():
                form.save()
                messages.success(request, '工程を追加しました')
        
            else:
                # バリデーションNG
                values = form.errors.get_json_data().values()
                for value in values:
                    for v in value:
                        messages.error(request, v["message"])
            

        context = {}
        context['item'] = item
        context['processes'] = Process.objects.all()
        return render(request, 'jewelstock/stock/detail.html', context)

# =======================================
# 商品管理
# =======================================

# 商品一覧
class ProductsView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        context['products'] = Product.objects.all()
        return render(request, 'jewelstock/product/list.html', context)

products_view = ProductsView.as_view()

# 商品新規作成
class ProductCreateView(View):
    def get(self, request, *args, **kwargs):
        form = ProductForm()
        context = {}
        context['form'] = form
        context['categories'] = Category.objects.all()

jewelstock/templates/jewelstock/product/create_form.html
{% extends "base.html" %}
{% load bootstrap %}

{% block head_title %}product - create{% endblock %}
{% block body_title %}product - create{% endblock %}


{% block content %}
<form action="" method="POST" id="productForm" class="form w-50 mx-auto">
    {% csrf_token %}
    <table class="table">
        {# 商品コード #}
        <tr>
            <th>商品コード</th>
            <td><input type="number" name="product_code" class="w-100"></td>
        </tr>

        {# 商品名 #}
        <tr>
            <th>商品名</th>
            <td><input type="text" name="name" class="w-100"></td>
        </tr>

        {# カテゴリー #}
        <tr>
            <th>カテゴリー</th>
            <td>
                <div id="categoryField">
                    {% for category in categories %}
                    <label><input type="checkbox" name="categories" value={{ category.name }}>{{ category.name }}</label><br>
                    {% endfor %}
                    <input type="text" name="categories" class="category w-100 d-block">
                </div>
                <button class="btn btn-light" id="addCategory"><i class="fa-solid fa-plus"></i></button>
            </td>
        </tr>

        {# 商品説明 #}
        <tr>
            <th>商品説明</th>
            <td><textarea name="description" class="w-100"></textarea></td>
        </tr>

        {# 重量 #}
        <tr>
            <th>重量</th>
            <td><input type="text" name="weight" class="w-100"></td>
        </tr>

        {# サイズ #}
        <tr>
            <th>サイズ</th>
            <td><input type="text" name="size" class="w-100"></td>
        </tr>

    </table>

    {# 送信ボタン #}
    <button type="submit" class="btn btn-danger d-block mx-auto">作成</button>
</form>
{% endblock %}

{% block script %}
{# +ボタン押下でカテゴリ欄を複製する処理 #}
<script>
const addCategoryButton = document.getElementById('addCategory');
const categoryField = document.getElementById('categoryField');
const textField = document.querySelector('#categoryField input[type="text"]');

addCategoryButton.addEventListener('click',  (e) => {

    // デフォルトの送信処理をキャンセル
    e.preventDefault();
    // カテゴリのテキストフィールドを複製して追加
    let clone_category = textField.cloneNode(false);
    // 入力済み文字の削除
    clone_category.value = '';
    // 子要素の最後に追加
    categoryField.appendChild(clone_category);
});
</script>

{% endblock %}

jewelstock/templates/jewelstock/product/detail.html
{% extends "base.html" %}
{% load bootstrap %}

{% block head_title %}product_detail - {{product.name}}{% endblock %}
{% block body_title %}product_detail - {{product.name}}{% endblock %}


{% block content %}

{# ========== 操作 ========== #}
<a href="{% url 'jewelstock:product_edit' pk=product.product_code %}" class="btn btn-primary">編集</a>
<form action="{% url 'jewelstock:product_delete' pk=product.product_code %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">削除</button>
</form>

{# ========== 詳細情報 ========== #}
<table class="table">
    {# 商品名 #}
    <tr>
        <th>商品名</th>
        <td>{{ product.name }}</td>
    </tr>

    {# 商品コード #}
    <tr>
        <th>商品コード</th>
        <td>{{ product.product_code }}</td>
    </tr>

    {# カテゴリー #}
    <tr>
        <th>カテゴリー</th>
        <td>
            {% for category in product.category.all %}
                {{ category.name }}<br>
            {% endfor %}
        </td>
    </tr>

    {# 商品説明 #}
    <tr>
        <th>商品説明</th>
        <td>{{ product.description }}</td>
    </tr>

    {# 重量 #}
    <tr>
        <th>重量</th>
        <td>{{ product.weight|default:'-' }}</td>
    </tr>

    {# サイズ #}
    <tr>
        <th>サイズ</th>
        <td>{{ product.size|default:'-' }}</td>
    </tr>

    {# 在庫数 #}
    <tr>
        <th>在庫数</th>
        <td>
            {{ product.count_item }}
            <form action="{% url 'jewelstock:stock' %}" class="d-inline">
                <input type="hidden" name="keyword" value={{ product.name }}>
                <button type="submit" class="btn btn-secondary">在庫確認</button>
            </form>
        </td>
    </tr>
</table>




{% endblock %}


{% block script %}
<script>
</script>
{% endblock %}

jewelstock/templates/jewelstock/product/edit.html
{% extends "base.html" %}
{% load bootstrap %}

{% block head_title %}product_edit - {{ product.name }}{% endblock %}
{% block body_title %}product_edit - {{ product.name }}{% endblock %}


{% block content %}
<form action="" method="POST" id="productForm" class="form w-50 mx-auto">
    {% csrf_token %}
    <table class="table">
        {# 商品コード #}
        <tr>
            <th>商品コード(編集不可)</th>
            <td>{{ product.product_code }}</td>
        </tr>

        {# 商品名 #}
        <tr>
            <th>商品名</th>
            <td><input type="text" name="name" class="w-100" value={{request.POST.name|default:product.name}}></td>
        </tr>

        {# カテゴリー #}
        <tr>
            <th>カテゴリー</th>
            <td>
                <div id="categoryField">
                    {% for category in categories %}
                    <label>
                        <input type="checkbox" name="categories" value={{ category.name }} {% if category in product.category.all %}checked{% endif %}>
                        {{ category.name }}
                    </label>
                    <br>
                    {% endfor %}
                    
                    {% for category in request.POST.categories %}
                        {% if category.type == "text" %}
                        <input type="text" name="categories" class="category w-100 d-block" value="{{ category.value }}">
                        {% endif %}
                    {% endfor %}
                
                    <input type="text" name="categories" class="category w-100 d-block">
                </div>
                <button class="btn btn-light" id="addCategory"><i class="fa-solid fa-plus"></i></button>
            </td>
        </tr>

        {# 商品説明 #}
        <tr>
            <th>商品説明</th>
            <td><textarea name="description" class="w-100">{{request.POST.description|default:product.description}}</textarea></td>
        </tr>

        {# 重量 #}
        <tr>
            <th>重量</th>
            <td><input type="text" name="weight" class="w-100" value="{{request.POST.weight|default:product.weight|default:''}}"></td>
        </tr>

        {# サイズ #}
        <tr>
            <th>サイズ</th>
            <td><input type="text" name="size" class="w-100" value="{{request.POST.size|default:product.size|default:''}}"></td>
        </tr>

        {# 税込み価格 #}
        <tr>
            <th>税込み価格</th>
            <td><input type="number" name="price" class="w-100" value="{{request.POST.price|default:product.price}}"></td>
        </tr>

    </table>

    {# 送信ボタン #}
    <button type="submit" class="btn btn-danger d-block mx-auto">保存</button>
</form>
{% endblock %}

{% block script %}
{# +ボタン押下でカテゴリ欄を複製する処理 #}
<script>
const addCategoryButton = document.getElementById('addCategory');
const categoryField = document.getElementById('categoryField');
const textField = document.querySelector('#categoryField input[type="text"]');

addCategoryButton.addEventListener('click',  (e) => {

    // デフォルトの送信処理をキャンセル
    e.preventDefault();
    // カテゴリのテキストフィールドを複製して追加
    let clone_category = textField.cloneNode(false);
    // 入力済み文字の削除
    clone_category.value = '';
    // 子要素の最後に追加
    categoryField.appendChild(clone_category);
});
</script>

{% endblock %}

jewelstock/templates/jewelstock/product/list.html
{% extends "base.html" %}
{% load bootstrap %}

{% block head_title %}products{% endblock %}
{% block body_title %}products{% endblock %}


{% block content %}
{# 新規作成ボタン #}
<a href="{% url 'jewelstock:product_create' %}" class='btn btn-lg btn-danger'>新規作成</a>

{# 検索フォーム #}
<form action="" class="form p-3 bg-warning">
    <label>商品名<input type="text" name="keyword" value="{{ request.GET.keyword }}"></label>
    <button type="submit" class="btn btn-primary">検索</button>
</form>

{# 商品リスト #}

<table class="table">
    <tr>
        <th>商品名</th>
        <th>商品コード</th>
        <th>型番</th>
        <th>カテゴリ</th>
        <th>在庫数</th>
        <th>操作</th>
    </tr>

    {% for product in products %}
    <tr>
        {# 商品名 #}
        <td>{{ product.name }}</td>

        {# 商品コード #}
        <td>{{ product.product_code }}</td>

        {# 形状 #}
        <td>{{ product.model_number }}</td>

        {# カテゴリ #}
        <td>
            {% for category in product.category.all %}
                {{ category }}<br>
            {% endfor %}
        </td>
        
        {# 在庫数 #}
        <td>
            {{ product.count_item }}
        </td>

        {# 操作 #}
        <td>
            <a href="{% url 'jewelstock:product_detail' pk=product.product_code %}" class="btn btn-primary">詳細</a>
        </td>
    </tr>
    {% endfor %}

</table>
{% endblock %}

{% block script %}
{# 検索フォーム #}
<script>


</script>
{% endblock %}